name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  # pull_request:
    # types: [opened, synchronize, reopened, closed]
    # branches:
      # - main

jobs:
  build_and_deploy_job:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: '1c7e820177906439b4e7dc71b4f837612a81689ac70d9e1e780224d7debce5841-505a32ca-ecba-432b-8dc3-7bd4a47d428700f44760'
          # azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: '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 # Used for Github integrations (i.e. PR comments)
          # repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
		  
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./" # App source code path
          #api_location: "" # Api source code path - optional
          #output_location: "/build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

		  #app_build_command: npm run build
          deployment_environment: test 

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
		  
